version: '3'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    volumes:
    - db:/var/lib/postgresql/data

  smtp:
    image: mwader/postfix-relay
    restart: unless-stopped
    depends_on:
    - mailman-core
    environment:
    - OPENDKIM_DOMAINS=${HOSTNAME}
    - POSTFIX_myhostname=${HOSTNAME}
    - POSTFIX_recipient_delimiter=+
    - POSTFIX_unknown_local_recipient_reject_code=550
    - POSTFIX_owner_request_special=no
    - POSTFIX_transport_maps=regexp:/mailman/postfix_lmtp
    - POSTFIX_local_recipient_maps=regexp:/mailman/postfix_lmtp
    - POSTFIX_relay_domains=regexp:/mailman/postfix_domains
    - POSTFIX_smtpd_recipient_restrictions=permit_mynetworks, reject_unauth_destination
    - POSTFIX_mynetworks=10.7.8.0/24
    ports:
    - 25:25
    volumes:
    - ./core/var/data:/mailman:ro

  mailman-core:
    image: maxking/mailman-core:0.4
    depends_on:
    - db
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
    - DATABASE_CLASS
    - DATABASE_TYPE
    - DATABASE_URL
    - MAILMAN_REST_PASSWORD
    - MTA=postfix
    - SMTP_HOST=smtp
    #ports:
    #- 8001:8001 # REST API
    #- 8024:8024 # LMTP
    volumes:
    - ./core:/opt/mailman

  mailman-web:
    image: maxking/postorius:0.4
    depends_on:
    - db
    - smtp
    restart: unless-stopped
    environment:
    - DATABASE_CLASS
    - DATABASE_TYPE
    - DATABASE_URL
    - SECRET_KEY
    - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
    - SERVE_FROM_DOMAIN=${HOSTNAME}
    - MAILMAN_ADMIN_USER
    - MAILMAN_ADMIN_EMAIL
    - MAILMAN_REST_PASSWORD
    - SMTP_HOST=smtp
    #ports:
    #- 8000:8000 # http
    #- 8080:8080 # uwsgi
    volumes:
    - ./web:/opt/mailman-web-data

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./web/static:/static:ro
    #ports:
    #- 80:80 # serve behind an https reverse proxy

volumes:
  db:

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 10.7.8.0/24